# Generated by Django 4.0.2 on 2022-02-08 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_label', models.CharField(max_length=50)),
                ('post_small_text', models.CharField(max_length=200)),
                ('create_as', models.DateTimeField(default=datetime.datetime(2022, 2, 8, 9, 0, 43, 57336, tzinfo=utc))),
                ('post_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
