# Generated by Django 4.0.2 on 2022-02-08 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_as',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
