# Generated by Django 4.0.2 on 2022-02-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_create_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_text',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
