# Generated by Django 4.0.2 on 2022-02-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_post_image_alter_post_post_small_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
